# Generated by Django 5.2.7 on 2025-11-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_enrollment_last_module_grade_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
