# Generated by Django 5.2.7 on 2025-12-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_grade_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_content_ids',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
